### ISSUE TITLE
Question on dependencies

### ISSUE THREAD

**Issue by goanpeca** [VicidominiLab/BrightEyes-ISM#3]
Hi team,

While working on https://github.com/conda-forge/brighteyes-ism-feedstock/pull/11, we noticed that there is a strict dependency

`PyCustomFocus==2.3` 

Is there any particular reason for this? Could this be relaxed to something like `PyCustomFocus >=2.3` or `PyCustomFocus <=2.3`

Cheers!

**Comment by Alessandro-Zunino** [comment]
Dear Gonzalo,

Thank you for your question. Yes, there is a reason for the strict dependency on PyCustomFocus.
The versions of PyCustomFocus higher than 2.3 are not retro-compatible, and their use would break some code in our package.
On the other hand, we have yet to test versions earlier than 2.3, and we are unsure if they are usable.

Since version 2.3 is the most recent version compatible with our package, we decided to use a strict dependency.
If such a choice does not cause problems, I will tag this issue as solved.

Let me know.
Best,

Alessandro Zunino

**Comment by goanpeca** [comment]
>Since version 2.3 is the most recent version compatible with our package, we decided to use a strict dependency.
>If such a choice does not cause problems, I will tag this issue as solved.

In this case, I would suggest the usage of <= as it would allow a bit more flexibility for the solver in case the are other packages that may be using pycustomfocus.

Cheers
